### ISSUE TITLE
Outdated documentation?

### ISSUE THREAD

**Issue by dfee** [asphalt-framework/asphalt-sqlalchemy#1]
The narrative documentation for [Configuration](http://asphalt-sqlalchemy.readthedocs.io/en/latest/configuration.html#configuration) specifies:

> This will make the database engine accessible as ctx.sql and the ORM session as ctx.dbsession.

However, the [API documentation](http://asphalt-sqlalchemy.readthedocs.io/en/latest/modules/component.html#asphalt.sqlalchemy.component.SQLAlchemyComponent) and the code seem to indicate that:

>The session will then be available as ctx.sql by default.

Indeed, `ctx.dbsession` raises an `AttributeError` and `ctx.sql` return an object of type `sqlalchemy.orm.session.Session`.

**Comment by agronholm** [comment]
Yep, the testing documentation is also partially wrong. I'll fix these in one go.

**Comment by agronholm** [comment]
Aaand 5 years later, I've revamped the documentation and code both. You're welcome! :)

**Comment by dfee** [comment]
congrats. glad to see you're still working on this. hope you're doing well!

**Comment by agronholm** [comment]
Thanks, I hope you're doing well too! My current client has decided to rely more heavily on Asphalt, prompting major upgrades. Asphalt 5 is on the horizon too, with a lot of modernization in it.
